# Generated by Django 4.2.11 on 2025-01-30 08:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('account_type', models.CharField(default='online', max_length=50)),
                ('account_currency', models.CharField(default='Dollar($)', max_length=50)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_number', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Number',
                'verbose_name_plural': 'Account Numbers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('domestic_transfer', 'Domestic Transfer'), ('local_transfer', 'Local Transfer'), ('international_transfer', 'International Transfer')], max_length=50)),
                ('incoming', models.CharField(default='Credit', max_length=7, verbose_name='Incoming')),
                ('to_user', models.CharField(default='0000000000', max_length=50, verbose_name='beneficiary')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('in_process', 'IN_PROCESS'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED'), ('in_review', 'IN_REVIEW')], default='completed', max_length=50)),
                ('updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accountnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='LocalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('current', 'Current Account'), ('saving', 'Saving Account'), ('checking', 'Checking Account')], default='saving', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.accountnumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=200, verbose_name='beneficiary name')),
                ('beneficiary_account_number', models.BigIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('current', 'Current Account'), ('saving', 'Saving Account'), ('checking', 'Checking Account')], max_length=50)),
                ('beneficiary_bank', models.CharField(max_length=50, verbose_name='beneficiary bank')),
                ('beneficiary_address', models.CharField(max_length=500, verbose_name='beneficiary address')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('routing_number', models.CharField(max_length=500, verbose_name='IBAN')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(max_length=1500, verbose_name='Reason')),
                ('updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=50, verbose_name='beneficiary')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='bank_name')),
                ('bank_account', models.IntegerField(verbose_name='Account Number')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
