# Generated by Django 4.2.11 on 2024-11-22 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_profile_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('updated', models.DateTimeField(verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AccountNumber',
                'verbose_name_plural': 'AccountNumbers',
            },
        ),
    ]
