# Generated by Django 4.2.11 on 2024-11-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_remove_profile_account_number_accountnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountnumber',
            options={'verbose_name': 'Account Number', 'verbose_name_plural': 'Account Numbers'},
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_number', to=settings.AUTH_USER_MODEL),
        ),
    ]
