# Generated by Django 4.2.11 on 2024-11-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_accountnumber_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
