# Generated by Django 4.2.11 on 2024-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_accountnumber_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='account_type',
            field=models.CharField(default='Dollar($)', max_length=50),
        ),
    ]
