# Generated by Django 4.2.11 on 2024-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_accountnumber_account_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnumber',
            name='account_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
