# Generated by Django 4.2.11 on 2024-11-22 11:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_accountnumber_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnumber',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountnumber',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accountnumber')),
            ],
        ),
    ]
