# Generated by Django 4.2.11 on 2024-11-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_accountnumber_locked_accountnumber_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('domestic_transfer', 'Domestic Transfer'), ('local_transfer', 'Local Transfer'), ('international_transfer', 'International Transfer')], max_length=50),
        ),
    ]
