# Generated by Django 4.2.11 on 2024-11-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_domestictransfer_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtransfer',
            name='beneficiary',
        ),
    ]
