# Generated by Django 4.2.11 on 2024-11-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_localtransfer_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='locked',
        ),
    ]
