# Generated by Django 4.2.11 on 2024-11-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_domestictransfer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtransfer',
            name='locked',
        ),
    ]
