# Generated by Django 4.2.11 on 2024-11-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_localtransfer_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='incoming',
            field=models.CharField(default='Credit', max_length=7, verbose_name='Incoming'),
        ),
    ]
