# Generated by Django 4.2.11 on 2024-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_transaction_incoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('in_process', 'IN_PROCESS'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED'), ('in_review', 'IN_REVIEW')], default='in_process', max_length=50),
        ),
    ]
